rm -rf ../Results/Gas/ave_epot*
rm -rf ../Results/Gas/ave_pres*
rm -rf ../Results/Gas/ave_etot*
rm -rf ../Results/Gas/ave_ekin*
rm -rf frames/*.xyz
rm -rf seed.out
rm -rf config.final
rm -rf ../Results/Gas/output*
rm -rf ../Results/Gas/ave_temp*
