rm -rf ../Results/Liquid/ave_epot*
rm -rf ../Results/Liquid/ave_pres*
rm -rf ../Results/Liquid/ave_etot*
rm -rf ../Results/Liquid/ave_ekin*
rm -rf frames/*.xyz
rm -rf seed.out
rm -rf config.final
rm -rf ../Results/Liquid/output*
rm -rf ../Results/Liquid/ave_temp*
